# .github/workflows/deploy.yml
name: Deploy Frosti to GitHub Pages

on:
  push:
    branches:
      - main # 或者你的主开发分支名

permissions: # 需要这些权限来写入 gh-pages 分支和触发 pages 构建
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: # 指定部署环境，这是新版 GitHub Pages Actions 的推荐做法
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # 输出部署后的 URL
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4 # 使用最新版

      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v3 # 使用最新版
        with:
          version: 10 # 或者项目 package.json 中 engines.pnpm 指定的版本

      - name: Setup Node.js 🏗️
        uses: actions/setup-node@v4 # 使用最新版
        with:
          node-version: "18" # 或者项目 package.json 中 engines.node 指定的版本
          cache: pnpm

      - name: Install dependencies 👨‍💻
        run: pnpm install --frozen-lockfile # 使用 frozen-lockfile 更安全

      - name: Build project 🚀
        # 确保 astro.config.ts 中的 site 和 base 已正确设置
        run: pnpm run build

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v4 # Astro 官方推荐的 Action

      - name: Upload artifact 📦
        uses: actions/upload-pages-artifact@v3 # Astro 官方推荐的 Action
        with:
          path: ./dist # Astro 默认构建输出到 dist 目录

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4 # Astro 官方推荐的 Action
